### ISSUE TITLE
compilation with icc fails with "error: mixed simd-scalar operation not allowed"

### ISSUE THREAD

**Issue by boegel** [sunqm/qcint#4]
When I try to compile `qcint` with Intel compilers (2019 update 1), I run into the following compilation problem:

```
/tmp/qcint-3.0.18/src/g3c1e.c(230): error: mixed simd-scalar operation not allowed
                  fac1 = 2./SQRTPI * MM_LOAD(envs->fac) * MM_LOAD(tau) / aijk;
```

This does not occur when compiling with GCC (8.2.0).

Is this a known issue? Is compilation with Intel compilers supported?

**Comment by sunqm** [comment]
This is a known issue. I didn't implement the compiler intrinsics according to Intel's guide. You need to use GCC to compile the code.
